# Generated by Django 5.1.4 on 2025-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_manager_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_image',
            name='image',
            field=models.ImageField(default=True, null=True, upload_to='image/'),
        ),
    ]
